# Generated by Django 3.2.5 on 2021-08-03 03:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 3, 17, 34, 369617, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
